### PR TITLE
Add base target for links to be configurable

### PR DESCRIPTION
**Pull request by leomelin**
I needed all the links to open in target="_blank", so I made this fork. It's fully backwards compatible, so I thought this feature might be useful for others also

### CODE REVIEW

**Comment by davityavryan** [comment]
Hey @leomelin,
Thanks for your contribution.
Why not just use a template and configure the way that you want? it is currently possible to pass a template file via `--template` or `-t` argument.

**Comment by leomelin** [comment]
Yes it's true I could copy the existing template and just add that base target there - TBH I didn't even think that option because I just want to show the report and be done with it. This observation basically makes this PR obsolete, so I think this should just be scrapped. It would've been nice to have option to determine that links open in new window or whatever target you want but using your own custom template also works. It's just more stuff to maintain yourself, but I see your point.

**Comment by leomelin** [comment]
Now I see why I didn't think of using template argument: It is not documented in the readme -file

**Comment by davityavryan** [comment]
@leomelin true. I will do that ASAP. Thanks for pointing that.

p.s. also planning to have tests and CI running automatically.

**Pull request closed without merging**
